server:
  port: 8099

halloId:
  client:
    id: <CLIENT_ID>
    privateKey: |
      -----BEGIN PRIVATE KEY-----
        <YOUR PUBLIC KEY>
      -----END PRIVATE KEY-----

  publicKey: |
    -----BEGIN PUBLIC KEY-----
        <HALLOID PUBLIC KEY>
    -----END PUBLIC KEY-----