server:
  port: 8099

halloId:
  client:
    id: 1234-4567-8910
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCEBvU8aQd+hDBU
      u1veJIoE9lDUTSv5xBg9OMuN6Zg56NfeSzTBolfgi3BWQM+C0vPQ5bjIDnBMPr+3
      tY723uPabF04O/4eWi6Vfv+dJvMa8eavP/V7HhmjeYjU5maBE1aJr1n0KItsq0im
      hNvtrk1pBUexfczG079suyGr8hjjq21S6ptdMqNZyB7PekMCSj7fsV0MY74t8GkR
      888jOsL3bqO54t3CjiMESk9M0sty1W8CUmMLOag+y9gLmPnMOkJAv9ypUdRYFnHp
      M9n8fZMACrA60+yhi2AE1Pilths7Ov9bMIZ66i6Ea1FoEKC9QVPNzASXmEzDiW0o
      K5GYsOHpAgMBAAECggEAP4nps+0IAkczy1Nv3vTOx5yTQdjx9P3+fFg8/ksRS61X
      Vk/zT80FZbc1lQ0T0O4dEMe9qeno+YipU4w5BW43UgMcydd1cL4N9TxtYABCtxD7
      6BNr3Jib1iTDSVKoui3IU/Lj47EviFjWWe1OupBMCOLVogHc70MwuO9GQS399HL0
      YZs4gpK/NEJuzT8wwodTKV3C8Luk3DiPq8BNuAmgr7ekqIVpnvVrfkpA/aB8i11q
      m7+ZLliyle95N/C1Ht9tXIgagBV/rYDGpKDkGaRpmv4WKBojLfOg4RIzWmR/Sdrf
      2EL6bs4wqJfWjenfQNqw4YwbpOO7GZg5bX9bO25ZQQKBgQDZ5+o+ac/aprBhM8Ad
      Y1s4TGERV8A8zl4LFxRwOdx51sIr+qmNzBTKUs3xZo21+hB+lc29CtTYqBTzsbds
      a7Rnh9NLMknI9g74LkC9ZoWP0eKZerFNnqbf/sFvXiGuv3fwGlOGPsYAWEbK6+9D
      Stzf3ao+UDlj6s/A/L2dCttYbQKBgQCbG6fwZmOUyxrVJjbFNpXCz9L4w/EnHfHq
      4gkkun3esNsN78b6zLJ3zHviuMWiaTOqxfp+u8bBYSCs5xh6MU/T7+kqxXBDuIRP
      DsAAzmRLhV1bf0v9U4yv6A1U5+8fQi5Q19fRHHsyC7yjh0NQ09/HoqA5Ag80MOkM
      pZAatlb57QKBgA3qMloj9aL3zAGZBWabBqM0tWofGWaIoxbANYzpFPwuy511V0h3
      xMgau43zx47cVhtPQ6ETxP3E1fmt2pGw2wdVdBe0MWQE2nXctkOh/VtuwrKcVCAp
      xmw9X2rWLv5yuZz6gWTsM0aoXHTu1guNB0fAZvOtucx4nSWsvgr+O32NAoGAYpHA
      t9VZk0U/WBVg2RNHOPY5bD2ZEvLEui/K/7xEITDjBIhMOzW6dMdOM1aYwg14+B24
      grFyLZI74aU6uOx9foIH+1Zdcavg6RzGh7yhoBywp2TONb7SuTcOwdZi78pvBJEm
      ZY1j/PnYd1OOQ99hZszCZXgZkWFDuPW+DjuyKkECgYAw6e8/4FIN1Jy8uXXqE2OR
      bfIr7GFFxbPatbr67DhuE9v7jqvFDrSjOIgRAuj+srzUHyhJrkoUui/NUAECg9fz
      Qeh0ZOKYkQ1aFpnEvCrPXkPrf9fpDIRePnS2n7GdktE5/umtr4nGe0V5Y6qkJEsT
      mALxtkzIUFdz848bAXFDQQ==
      -----END PRIVATE KEY-----

  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhAb1PGkHfoQwVLtb3iSK
    BPZQ1E0r+cQYPTjLjemYOejX3ks0waJX4ItwVkDPgtLz0OW4yA5wTD6/t7WO9t7j
    2mxdODv+HloulX7/nSbzGvHmrz/1ex4Zo3mI1OZmgRNWia9Z9CiLbKtIpoTb7a5N
    aQVHsX3MxtO/bLshq/IY46ttUuqbXTKjWcgez3pDAko+37FdDGO+LfBpEfPPIzrC
    926jueLdwo4jBEpPTNLLctVvAlJjCzmoPsvYC5j5zDpCQL/cqVHUWBZx6TPZ/H2T
    AAqwOtPsoYtgBNT4pbYbOzr/WzCGeuouhGtRaBCgvUFTzcwEl5hMw4ltKCuRmLDh
    6QIDAQAB
    -----END PUBLIC KEY-----