server:
  port: 8099

halloId:
  client:
    id: <CLIENT ID>
    privateKey: |
      -----BEGIN PRIVATE KEY-----
      <PRIVATE KEY>
      -----END PRIVATE KEY-----

  publicKey: |
    -----BEGIN PUBLIC KEY-----
    <PUBLIC KEY>
    -----END PUBLIC KEY-----